# Generated by Django 2.2.5 on 2019-09-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curdoperations',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
