# Generated by Django 2.2.5 on 2019-09-14 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0002_auto_20190914_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curdoperations',
            name='dob',
        ),
    ]
